#QUIERE PASAR EL RAMO?
#PREGUNTE LA CANTIDAD DE ROJOS EN EL CURSO 
#LOS TALLERES QUE HAY EN EL SEMESTRE SON 4
#POR CADA TALLER ASISTIDO OBTIENE 0.3 DECIMAS
#SI EL ALUMNO TIENE MAS DE UN PUNTO
#TIENE LA BENDICION DEL PROFESOR 
#SI NO, NO SE LE PUEDE AYUDAR
#INGRESE LA NOTA FINAL Y SUME LAS DECIMAS ACOMULADAS
#MUESTRE SI APRUEBA O REPRUEBA 

print()